### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Pete3R** [SmushyTaco/Legacy-Display#3]
Upon starting the game it crashes without mojang loading screen even appearing
Crash log:

```
[03:00:36] [main/INFO]: Loading for game Minecraft 1.17.1
[03:00:36] [main/WARN]: Warnings were found!
 - Mod 'AdvancementInfo' (advancementinfo) recommends "version 1.1.7 or later" of modupdater, which is missing!
	 - You should install "version 1.1.7 or later" of modupdater for the optimal experience.
 - Mod 'AntiGhost' (antighost) recommends "version 1.1.7 or later" of modupdater, which is missing!
	 - You should install "version 1.1.7 or later" of modupdater for the optimal experience.
 - Mod 'ClickThrough' (clickthrough) recommends "version 1.1.7 or later" of modupdater, which is missing!
	 - You should install "version 1.1.7 or later" of modupdater for the optimal experience.
 - Mod 'EasierCrafting' (easiercrafting) recommends "version 1.1.7 or later" of modupdater, which is missing!
	 - You should install "version 1.1.7 or later" of modupdater for the optimal experience.
 - Mod 'EasierVillagerTrading' (easiervillagertrading) recommends "version 1.1.7 or later" of modupdater, which is missing!
	 - You should install "version 1.1.7 or later" of modupdater for the optimal experience.
 - Mod 'Modern Beta Fabric' (modern_beta) conflicts with any version of mod 'Hydrogen' (hydrogen), which is present with the following versions: 0.3!
	 - While this won't prevent you from starting the game, the developer(s) of mod 'Modern Beta Fabric' (modern_beta) have found that this combination may cause issues. You should remove one of the mods or check for updates that resolve the issue.
	 - Mod 'Hydrogen' (hydrogen) 0.3 is being loaded from D:\Minecraft GDLauncher\instances\Moddi\mods\hydrogen-fabric-mc1.17.1-0.3 (3).jar
[03:00:36] [main/INFO]: Loading 202 mods:
	- accurateblockplacement 1.0.10
	- advanced_runtime_resource_pack 0.4.3
	- advancedcompass 1.2.6
	- advancementinfo 1.17.1-fabric0.36.1-1.2.1
	- ambientenvironment 6.0.22
	- amecs 1.3.4+mc.1.17
	- amecsapi 1.1.5+mc21w16a
	- antighost 1.17.1-fabric0.36.1-1.1.4
	- appleskin mc1.17-2.1.3
	- architectury 2.6.35
	- audiooutput 0.0.4
	- authme 1.5.0
	- autoclicker-fabric 1.17.1-1.2.1-build.13
	- autoconfig1u 3.2.2
	- autofish 0.9.3
	- betterbeds 1.2.0
	- betterdarkmode 1.0.2-v20211004
	- bettergamemenu 1.2
	- betterpingdisplay 1.1
	- betterrecipebook 1.5.4
	- blur 2.4.0
	- bobby 2.0.4
	- breakfree 1.0.0
	- cameraoverhaul 1.3.0-fabric-universal
	- capes 1.2.2+1.17
	- carpet 1.4.51
	- charmonium 3.3.0
	- chat_heads 0.5.0
	- cherishedworlds 2.0.1-1.17.1
	- chesttracker 1.1.1
	- chime 1.1.2
	- cleardespawn 1.17.1-1.1.2
	- clickthrough 1.17.1-fabric0.36.1-0.4
	- cloth-api 2.0.54
	- cloth-basic-math 0.5.1
	- cloth-client-events-v0 2.0.54
	- cloth-common-events-v1 2.0.54
	- cloth-config2 5.0.38
	- cloth-datagen-api-v1 2.0.54
	- cloth-scissors-api-v1 2.0.54
	- cloth-utils-v1 2.0.54
	- collective-fabric 1.61
	- com_electronwill_night-config_core 3.6.2
	- com_electronwill_night-config_toml 3.6.2
	- com_moandjiezana_toml_toml4j 0.7.2
	- com_typesafe_config 1.4.1
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT
	- confabricate 2.1.0-SNAPSHOT+4.1.1
	- continuity 1.0.2+1.17
	- cosmetica 0.2.0
	- craftpresence 1.8.8
	- crowdin-translate 1.3+1.17
	- cullleaves 2.3.2
	- dcch 2.0+1.17
	- deathlog 0.2.1
	- detailab 2.6.1+1.17.1-fabric
	- disable_custom_worlds_advice 1.3
	- draggable-resource-packs 1.0.1
	- dsurround 0.0.4
	- dynamicfps 2.0.6
	- easiercrafting 1.17.1-fabric0.36.1-1.7
	- easiervillagertrading 1.17.1-fabric0.36.1-1.5.4
	- eatinganimationid 1.2
	- enchantmentdescriptions 4.0.1
	- enhanced_attack_indicator 1.0.2+1.17
	- enhancedblockentities 0.5+1.17
	- entity-view-distance 1.0.0
	- entityculling 1.3.3
	- essentialgui 1.6.5-1.17.1
	- fabric 0.41.3+1.17
	- fabric-api-base 0.3.0+a02b446318
	- fabric-api-lookup-api-v1 1.3.0+cbda931818
	- fabric-biome-api-v1 3.2.1+ffbe6d8f18
	- fabric-blockrenderlayer-v1 1.1.5+a02b446318
	- fabric-command-api-v1 1.1.3+5ab9934c18
	- fabric-commands-v0 0.2.2+92519afa18
	- fabric-containers-v0 0.1.12+cbda931818
	- fabric-content-registries-v0 0.3.0+cbda931818
	- fabric-crash-report-info-v1 0.1.5+be9da31018
	- fabric-dimensions-v1 2.0.12+ffbe6d8f18
	- fabric-entity-events-v1 1.3.0+57bef5a318
	- fabric-events-interaction-v0 0.4.10+fc40aa9d18
	- fabric-events-lifecycle-v0 0.2.1+92519afa18
	- fabric-game-rule-api-v1 1.0.7+cbda931818
	- fabric-item-api-v1 1.2.4+cbda931818
	- fabric-item-groups-v0 0.3.0+ef17126d18
	- fabric-key-binding-api-v1 1.0.4+cbda931818
	- fabric-keybindings-v0 0.2.2+36b77c3e18
	- fabric-language-kotlin 1.6.5+kotlin.1.5.31
	- fabric-lifecycle-events-v1 1.4.4+a02b446318
	- fabric-loot-tables-v1 1.0.4+a02b446318
	- fabric-mining-levels-v0 0.1.3+92519afa18
	- fabric-models-v0 0.3.0+a02b446318
	- fabric-networking-api-v1 1.0.13+cbda931818
	- fabric-networking-blockentity-v0 0.2.11+a02b446318
	- fabric-networking-v0 0.3.2+92519afa18
	- fabric-object-builder-api-v1 1.10.9+cbda931818
	- fabric-object-builders-v0 0.7.3+a02b446318
	- fabric-particles-v1 0.2.4+a02b446318
	- fabric-permissions-api-v0 0.1-SNAPSHOT
	- fabric-registry-sync-v0 0.7.12+81e15a8918
	- fabric-renderer-api-v1 0.4.4+cbda931818
	- fabric-renderer-indigo 0.4.8+cbda931818
	- fabric-renderer-registries-v1 3.2.4+7931163218
	- fabric-rendering-data-attachment-v1 0.1.5+a02b446318
	- fabric-rendering-fluids-v1 0.1.14+4658223018
	- fabric-rendering-v0 1.1.5+7931163218
	- fabric-rendering-v1 1.9.0+7931163218
	- fabric-resource-loader-v0 0.4.8+a00e834b18
	- fabric-screen-api-v1 1.0.4+cbda931818
	- fabric-screen-handler-api-v1 1.1.8+cbda931818
	- fabric-structure-api-v1 1.1.13+5ab9934c18
	- fabric-tag-extensions-v0 1.2.1+81e15a8918
	- fabric-textures-v0 1.0.6+a02b446318
	- fabric-tool-attribute-api-v1 1.2.12+b7ab612118
	- fabric-transfer-api-v1 1.4.1+ffbe6d8f18
	- fabricloader 0.12.2
	- fallingleaves 1.7.4+1.17.1
	- ferritecore 3.1.0
	- fiber 0.23.0-2
	- firstperson 2.0.3
	- fvt 1.7.3-mc1.17.1
	- gbfabrictools 1.3.4+1.17
	- horsestatsvanilla 4.1.8
	- hydrogen 0.3
	- illuminations 1.9
	- indium 1.0.0+mc1.17.1
	- inspecio 1.1.0+1.17
	- inventory_control_tweaks 1.3.8+MC1.17-1.17.1
	- inventoryhud 3.4.1
	- inventoryprofilesnext 1.1.1
	- io_leangen_geantyref_geantyref 1.3.11
	- iris 1.1.2+build.9
	- itemmodelfix 1.0.2+1.17
	- jankson 3.0.1+j1.2.0
	- java 16
	- kirin 1.9.1
	- krypton 0.1.4
	- lambdabettergrass 1.2.1+1.17
	- lambdynlights 2.0.2+1.17
	- lazydfu 0.1.2
	- legacy_display 1.1.3
	- libgui 4.1.7+1.17.1
	- libninepatch 1.1.0
	- libzoomer 0.2.1+1.17
	- lightoverlay 6.0.1
	- lithium 0.7.4
	- malilib 0.10.0-dev.26
	- midnightlib 0.3.0
	- minecraft 1.17.1
	- mm 2.1
	- modern_beta 2.7+1.17.1
	- modmenu 2.0.14
	- musicdr 1.2.1
	- namepain 1.4.0
	- nicephore fabric-1.17.x-1.1.0
	- noanglebrackets 1.1.0
	- nomoreglowingpots 1.0.2
	- notenoughanimations 1.3.3
	- notenoughcrashes 3.7.1+1.17.1
	- notes 1.0.8
	- okzoomer 5.0.0-beta.2+1.17
	- oldswing 3.1.0
	- org_aperlambda_lambdajcommon 1.8.1
	- org_codehaus_groovy_groovy 3.0.8
	- org_codehaus_groovy_groovy-jsr223 3.0.8
	- org_jetbrains_kotlin_kotlin-reflect 1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib 1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.5.31
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.0
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.0
	- org_openjdk_nashorn_nashorn-core 15.3
	- org_spongepowered_configurate-core 4.1.1
	- org_spongepowered_configurate-extra-dfu4 4.1.1
	- org_spongepowered_configurate-gson 4.1.1
	- org_spongepowered_configurate-hocon 4.1.1
	- ostoverhaul 0.1
	- particlerain 1.5.0
	- phosphor 0.7.2+build.180
	- physicsmod 2.5.15
	- presencefootsteps r32-1.17-rc1
	- resolutioncontrol 3.0.0
	- sakurablossoms ${version}
	- satin 1.6.4
	- semitranslucency 1.1-fabric
	- silentbackground 1.0.1
	- skinlayers 1.2.1
	- slight-gui-modifications 2.0.1
	- smoke_suppression 1.0.4+MC1.17-1.17.1
	- smoothboot 1.16.5-1.6.0
	- sodium 0.3.2+IRIS2-build.9
	- spruceui 3.3.0+1.17
	- stendhal 1.2.0RC5-1.17
	- tooltipfix 1.0.4-1.17.1
	- transliterationlib 1.2.2
	- visuality 0.2.0
	- voicechat 1.17.1-1.1.11
	- waveycapes 1.0.3
	- whereisit 1.14.3
[03:00:36] [main/WARN]: Mod `appleskin` (mc1.17-2.1.3) does not respect SemVer - comparison support is limited.
[03:00:36] [main/WARN]: Mod `nicephore` (fabric-1.17.x-1.1.0) does not respect SemVer - comparison support is limited.
[03:00:36] [main/WARN]: Mod `presencefootsteps` (r32-1.17-rc1) does not respect SemVer - comparison support is limited.
[03:00:36] [main/WARN]: Mod `sakurablossoms` (${version}) does not respect SemVer - comparison support is limited.
[03:00:36] [main/WARN]: Mod `stendhal` (1.2.0RC5-1.17) does not respect SemVer - comparison support is limited.
[03:00:37] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/D:/Minecraft%20GDLauncher/datastore/libraries/net/fabricmc/sponge-mixin/0.10.3+mixin.0.8.4/sponge-mixin-0.10.3+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[03:00:37] [main/INFO]: Compatibility level set to JAVA_16
[03:00:37] [main/WARN]: Registration of InjectionPoint APPLESKIN_IINC with squeek.appleskin.mixin.util.BeforeInc without specifying namespace is deprecated.
[03:00:37] [main/INFO]: Loaded configuration file for Lithium: 86 options available, 1 override(s) found
[03:00:37] [main/WARN]: [Satin] Sodium is present, custom block renders may not work
[03:00:37] [main/INFO]: Loaded configuration file for Sodium: 28 options available, 0 override(s) found
[03:00:37] [main/WARN]: Catching java.lang.ClassNotFoundException: me/shedaniel/rei/impl/client/gui/fabric/ScreenOverlayImplImpl
java.lang.ClassNotFoundException: me/shedaniel/rei/impl/client/gui/fabric/ScreenOverlayImplImpl
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.getClassBytes(MixinServiceKnot.java:65) ~[fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.getClassNode(MixinServiceKnot.java:76) ~[fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.getClassNode(MixinServiceKnot.java:71) ~[fabric-loader-0.12.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:2022) [sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1018) [sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:1008) [sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:896) [sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:869) [sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:781) [sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:539) [sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) [sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222) [fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133) [fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) [fabric-loader-0.12.2.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) [?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) [?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) [fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) [fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) [fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) [fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) [fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:134) [fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.2.jar:?]
[03:00:37] [main/WARN]: Error loading class: me/shedaniel/rei/impl/client/gui/fabric/ScreenOverlayImplImpl (java.lang.ClassNotFoundException: me/shedaniel/rei/impl/client/gui/fabric/ScreenOverlayImplImpl)
[03:00:37] [main/WARN]: @Mixin target me.shedaniel.rei.impl.client.gui.fabric.ScreenOverlayImplImpl was not found appleskin.mixins.json:REITooltipMixin
[03:00:37] [main/INFO]: Using modern mixin 'mirsario.cameraoverhaul.fabric.mixins.modern.CameraMixin'.
[03:00:37] [main/INFO]: Using modern mixin 'mirsario.cameraoverhaul.fabric.mixins.modern.GameRendererMixin'.
[03:00:37] [main/INFO]: Skipping legacy mixin 'mirsario.cameraoverhaul.fabric.mixins.legacy.LegacyCameraMixin'.
[03:00:37] [main/WARN]: Catching java.lang.ClassNotFoundException: grondag/canvas/terrain/region/input/InputRegion
java.lang.ClassNotFoundException: grondag/canvas/terrain/region/input/InputRegion
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.getClassBytes(MixinServiceKnot.java:65) ~[fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.getClassNode(MixinServiceKnot.java:76) ~[fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.getClassNode(MixinServiceKnot.java:71) ~[fabric-loader-0.12.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:2022) [sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1018) [sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:1008) [sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:896) [sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:869) [sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:781) [sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:539) [sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) [sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222) [fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133) [fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) [fabric-loader-0.12.2.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) [?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) [?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) [fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) [fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) [fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) [fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) [fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:134) [fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.2.jar:?]
[03:00:37] [main/WARN]: Error loading class: grondag/canvas/terrain/region/input/InputRegion (java.lang.ClassNotFoundException: grondag/canvas/terrain/region/input/InputRegion)
[03:00:38] [main/WARN]: Mixin malte0811.ferritecore.mixin.mrl.ModelResourceLocationMixin is disabled as Hydrogen is installed
[03:00:38] [main/WARN]: Mixin malte0811.ferritecore.mixin.mrl.ResourceLocationAccess is disabled as Hydrogen is installed
[03:00:38] [main/WARN]: Mixin malte0811.ferritecore.mixin.dedupbakedquad.BakedQuadAccess is disabled as Hydrogen is installed
[03:00:38] [main/WARN]: Mixin malte0811.ferritecore.mixin.dedupbakedquad.SimpleModelBuilderMixin is disabled as Hydrogen is installed
[03:00:38] [main/WARN]: Mixin malte0811.ferritecore.mixin.chunknbt.ChunkSerializerMixin is disabled as Hydrogen is installed
[03:00:38] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
[03:00:38] [main/WARN]: Adding Mixin to disable Hydrogen's MixinState#postCreateWithTable
[03:00:38] [main/INFO]: I used the json to destroy the json
[03:00:38] [main/INFO]: Injecting class 'com.google.common.collect.HydrogenImmutableMapEntry' (url: jar:file:/D:/Minecraft%20GDLauncher/instances/Moddi/mods/hydrogen-fabric-mc1.17.1-0.3%20(3).jar!/com/google/common/collect/HydrogenImmutableMapEntry.class)
[03:00:38] [main/INFO]: Injecting class 'com.google.common.collect.HydrogenEntrySetIterator' (url: jar:file:/D:/Minecraft%20GDLauncher/instances/Moddi/mods/hydrogen-fabric-mc1.17.1-0.3%20(3).jar!/com/google/common/collect/HydrogenEntrySetIterator.class)
[03:00:38] [main/INFO]: Injecting class 'com.google.common.collect.HydrogenEntrySet' (url: jar:file:/D:/Minecraft%20GDLauncher/instances/Moddi/mods/hydrogen-fabric-mc1.17.1-0.3%20(3).jar!/com/google/common/collect/HydrogenEntrySet.class)
[03:00:38] [main/INFO]: Injecting class 'com.google.common.collect.HydrogenImmutableReferenceHashMap' (url: jar:file:/D:/Minecraft%20GDLauncher/instances/Moddi/mods/hydrogen-fabric-mc1.17.1-0.3%20(3).jar!/com/google/common/collect/HydrogenImmutableReferenceHashMap.class)
[03:00:38] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[03:00:38] [main/INFO]: Initializing StacktraceDeobfuscator
[03:00:38] [main/INFO]: Done initializing StacktraceDeobfuscator
[03:00:38] [main/INFO]: Smooth Boot config initialized
[03:00:43] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[03:00:43] [Render thread/WARN]: @Redirect conflict. Skipping slight-gui-modifications.mixins.json:MixinTitleScreen->@Redirect::thing(Lnet/minecraft/class_766;FF)V from mod slight-gui-modifications with priority 1000, already redirected by legacy_display.mixins.json:TitleScreenMixin->@Redirect::renderDefaultBackgroundInstead(Lnet/minecraft/class_766;FFLnet/minecraft/class_4587;IIF)V from mod legacy_display with priority 1001
[03:00:44] [Render thread/WARN]: @Redirect conflict. Skipping slight-gui-modifications.mixins.json:MixinTitleScreen->@Redirect::thing(Lnet/minecraft/class_766;FF)V from mod slight-gui-modifications with priority 1000, already redirected by legacy_display.mixins.json:TitleScreenMixin->@Redirect::renderDefaultBackgroundInstead(Lnet/minecraft/class_766;FFLnet/minecraft/class_4587;IIF)V from mod legacy_display with priority 1001
[03:00:44] [Render thread/INFO]: [STDERR]: java.lang.RuntimeException: Minecraft has crashed
[03:00:44] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:571)
[03:00:44] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[03:00:44] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[03:00:44] [Render thread/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_442 failed
[03:00:44] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:224)
[03:00:44] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133)
[03:00:44] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
[03:00:44] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[03:00:44] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:187)
[03:00:44] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03:00:44] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[03:00:44] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03:00:44] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[03:00:44] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
[03:00:44] [Render thread/INFO]: [STDERR]: 	... 2 more
[03:00:44] [Render thread/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[03:00:44] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[03:00:44] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
[03:00:44] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
[03:00:44] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222)
[03:00:44] [Render thread/INFO]: [STDERR]: 	... 11 more
[03:00:44] [Render thread/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector thing(Lnet/minecraft/class_766;FF)V in slight-gui-modifications.mixins.json:MixinTitleScreen from mod slight-gui-modifications failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap slight-gui-modifications-refmap.json
[03:00:44] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
[03:00:44] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1381)
[03:00:44] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
[03:00:44] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
[03:00:44] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
[03:00:44] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
[03:00:44] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
[03:00:44] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[03:00:44] [Render thread/INFO]: [STDERR]: 	... 14 more

```

I will try to experiment with what may cause a crash, but that would be next morning

**Comment by Pete3R** [comment]
Did a little test since i have seen other Issue reports
Slight Gui Modifications was causing the crash on startup
I am using version 1.1.3

**Comment by Pete3R** [comment]
Same issue when trying to use MemoryUsageScreen 1.2
